# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'

steps:

# Restore, build, & pack the projects
- script: dotnet pack --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) -p:ContinuousIntegrationBuild=true
  displayName: 'Build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger nunit --framework netcoreapp3.1 --collect "Code coverage"'
  displayName: 'Test .NET Core 3.1'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger nunit --framework netcoreapp6.0 --collect "Code coverage"'
  displayName: 'Test .NET Core 6.0'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.5.0'

- script: |
    nuget push $(Build.ArtifactStagingDirectory)/*.nupkg -src https://api.nuget.org/v3/index.json -ApiKey $(NugetApiKey)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'NuGet Push'
